import { IPlayer } from "../PlayerList";
import player from "../../../../public/image/player.svg";
//야구 빙구 농구 럭비 축구 순서
export const koreaPlayer: IPlayer[][] = [
  [
    //야구
    {
      img: player,
      name: "김대호",
      backNum: 41,
      position: "투수",
      studentId: 20,
      body: "183/95",
    },
    {
      img: player,
      name: "김응주",
      backNum: 16,
      position: "내야수",
      studentId: 20,
      body: "176/80",
    },
    {
      img: player,
      name: "오도은",
      backNum: 27,
      position: "포수",
      studentId: 20,
      body: "172/86",
    },
    {
      img: player,
      name: "이지원",
      backNum: 56,
      position: "투수",
      studentId: 20,
      body: "179/86",
    },
    {
      img: player,
      name: "조경원",
      backNum: 1,
      position: "투수",
      studentId: 20,
      body: "182/88",
    },
    {
      img: player,
      name: "허진",
      backNum: 7,
      position: "유격수",
      studentId: 20,
      body: "175/79",
    },
    {
      img: player,
      name: "김범진",
      backNum: 47,
      position: "1루수",
      studentId: 21,
      body: "183/85",
    },
    {
      img: player,
      name: "박건우",
      backNum: 25,
      position: "포수",
      studentId: 21,
      body: "185/90",
    },
    {
      img: player,
      name: "박찬진",
      backNum: 2,
      position: "내야수",
      studentId: 21,
      body: "177/78",
    },
    {
      img: player,
      name: "김응주",
      backNum: 16,
      position: "내야수",
      studentId: 20,
      body: "176/80",
    },
    {
      img: player,
      name: "서준우",
      backNum: 37,
      position: "투수",
      studentId: 21,
      body: "180/88",
    },
    {
      img: player,
      name: "오동운",
      backNum: 9,
      position: "외야수",
      studentId: 21,
      body: "177/73",
    },
    {
      img: player,
      name: "조규택",
      backNum: 6,
      position: "내야수",
      studentId: 21,
      body: "178/74",
    },
    {
      img: player,
      name: "차성윤",
      backNum: 33,
      position: "외야수",
      studentId: 21,
      body: "184/88",
    },
    {
      img: player,
      name: "김민재",
      backNum: 39,
      position: "외야수",
      studentId: 22,
      body: "180/78",
    },
    {
      img: player,
      name: "박세훈",
      backNum: 13,
      position: "외야수",
      studentId: 22,
      body: "193/90",
    },
    {
      img: player,
      name: "안민성",
      backNum: 21,
      position: "포수",
      studentId: 22,
      body: "184/90",
    },
    {
      img: player,
      name: "안재연",
      backNum: 52,
      position: "내야수",
      studentId: 22,
      body: "178/75",
    },
    {
      img: player,
      name: "유정택",
      backNum: 17,
      position: "내야수",
      studentId: 22,
      body: "172/70",
    },
    {
      img: player,
      name: "이건호",
      backNum: 10,
      position: "외투수",
      studentId: 22,
      body: "177/80",
    },
    {
      img: player,
      name: "정지헌",
      backNum: 11,
      position: "투수",
      studentId: 22,
      body: "182/85",
    },
    {
      img: player,
      name: "정튼튼",
      backNum: 15,
      position: "투수",
      studentId: 22,
      body: "180/73",
    },
    {
      img: player,
      name: "강민우",
      backNum: 23,
      position: "내야수",
      studentId: 23,
      body: "172/70",
    },
    {
      img: player,
      name: "김대홍",
      backNum: 22,
      position: "포수",
      studentId: 23,
      body: "178/84",
    },
    {
      img: player,
      name: "김동환",
      backNum: 54,
      position: "투수",
      studentId: 23,
      body: "184/80",
    },
    {
      img: player,
      name: "김범근",
      backNum: 51,
      position: "투수",
      studentId: 23,
      body: "184/83",
    },
    {
      img: player,
      name: "김영후",
      backNum: 8,
      position: "외야수",
      studentId: 23,
      body: "184/76",
    },
    {
      img: player,
      name: "김준엽",
      backNum: 18,
      position: "내야수",
      studentId: 23,
      body: "177/85",
    },
    {
      img: player,
      name: "정원진",
      backNum: 48,
      position: "투수",
      studentId: 23,
      body: "182/85",
    },
    {
      img: player,
      name: "주정환",
      backNum: 53,
      position: "내야수",
      studentId: 23,
      body: "180/70",
    },
    {
      img: player,
      name: "홍은성",
      backNum: 12,
      position: "투수",
      studentId: 23,
      body: "179/79",
    },
  ],
  [
    //빙구
    {
      img: player,
      name: "김성재",
      backNum: 71,
      position: "FW",
      studentId: 20,
      body: "176/798",
    },
    {
      img: player,
      name: "남은석",
      backNum: 82,
      position: "DF",
      studentId: 20,
      body: "176/73",
    },
    {
      img: player,
      name: "박형은",
      backNum: 11,
      position: "FW",
      studentId: 20,
      body: "173/76",
    },
    {
      img: player,
      name: "이형석",
      backNum: 19,
      position: "FW",
      studentId: 20,
      body: "181/80",
    },
    {
      img: player,
      name: "정호현",
      backNum: 84,
      position: "DF",
      studentId: 20,
      body: "180/81",
    },
    {
      img: player,
      name: "최원호",
      backNum: 20,
      position: "FW",
      studentId: 20,
      body: "176/75",
    },
    {
      img: player,
      name: "하정호",
      backNum: 30, //34로도 되어 있음?
      position: "G",
      studentId: 20,
      body: "183/85",
    },

    {
      img: player,
      name: "권민재",
      backNum: 50,
      position: "DF",
      studentId: 21,
      body: "183/77",
    },
    {
      img: player,
      name: "김동준",
      backNum: 87,
      position: "FW",
      studentId: 21,
      body: "178/75",
    },
    {
      img: player,
      name: "김현서",
      backNum: 56,
      position: "DF",
      studentId: 21,
      body: "183/80",
    },
    {
      img: player,
      name: "박영서",
      backNum: 47,
      position: "FW",
      studentId: 21,
      body: "175/73",
    },
    {
      img: player,
      name: "송은석",
      backNum: 1, //37로도 되어있음
      position: "G",
      studentId: 21,
      body: "180/86",
    },
    {
      img: player,
      name: "이윤석",
      backNum: 72,
      position: "FW",
      studentId: 21,
      body: "184/85",
    },
    {
      img: player,
      name: "장희곤",
      backNum: 78,
      position: "FW",
      studentId: 21,
      body: "178/78",
    },

    {
      img: player,
      name: "권현숙",
      backNum: 70,
      position: "FW",
      studentId: 22,
      body: "178/74",
    },
    {
      img: player,
      name: "김무성",
      backNum: 13,
      position: "FW",
      studentId: 22,
      body: "178/74",
    },
    {
      img: player,
      name: "양정원",
      backNum: 86,
      position: "DF",
      studentId: 22,
      body: "177/74",
    },
    {
      img: player,
      name: "이준서",
      backNum: 14,
      position: "FW",
      studentId: 22,
      body: "180/73",
    },
    {
      img: player,
      name: "조현겸",
      backNum: 7,
      position: "DF",
      studentId: 22,
      body: "178/74",
    },

    {
      img: player,
      name: "김상엽", //프로필에는 없고 블로그에 있음
      backNum: 97,
      position: "FW",
      studentId: 23,
      body: "182/82",
    },
    {
      img: player,
      name: "김성호",
      backNum: 43,
      position: "DF",
      studentId: 23,
      body: "182/75",
    },
    {
      img: player,
      name: "문승민",
      backNum: 33,
      position: "DF",
      studentId: 23,
      body: "184/78",
    },
    {
      img: player,
      name: "서경민",
      backNum: 31,
      position: "G",
      studentId: 23,
      body: "175/70",
    },
    {
      img: player,
      name: "이무영",
      backNum: 79,
      position: "FW",
      studentId: 23,
      body: "175/73",
    },
    {
      img: player,
      name: "최성순",
      backNum: 44,
      position: "FW",
      studentId: 23,
      body: "176/76",
    },
    {
      img: player,
      name: "허민준",
      backNum: 17,
      position: "FW",
      studentId: 23,
      body: "185/83",
    },
  ],
  [
    //농구
    {
      img: player,
      name: "박무빈",
      backNum: 3,
      position: "G",
      studentId: 20,
      body: "187/80",
    },
    {
      img: player,
      name: "문정현",
      backNum: 12,
      position: "F",
      studentId: 20,
      body: "194/95",
    },
    {
      img: player,
      name: "김도은",
      backNum: 5,
      position: "G",
      studentId: 21,
      body: "183/86",
    },
    {
      img: player,
      name: "김재현",
      backNum: 10,
      position: "G",
      studentId: 21,
      body: "190/82",
    },
    {
      img: player,
      name: "김태훈",
      backNum: 9,
      position: "F",
      studentId: 21,
      body: "190/86",
    },
    {
      img: player,
      name: "박준형",
      backNum: 13,
      position: "F",
      studentId: 21,
      body: "192/89",
    },
    {
      img: player,
      name: "양준",
      backNum: 11,
      position: "C",
      studentId: 21,
      body: "202/96",
    },

    {
      img: player,
      name: "김민규",
      backNum: 23,
      position: "F",
      studentId: 22,
      body: "196/88",
    },
    {
      img: player,
      name: "박정환",
      backNum: 6,
      position: "G",
      studentId: 22,
      body: "181/76",
    },
    {
      img: player,
      name: "신주영",
      backNum: 2,
      position: "F",
      studentId: 22,
      body: "200/95",
    },
    {
      img: player,
      name: "이건희",
      backNum: 0,
      position: "G",
      studentId: 22,
      body: "187/80",
    },

    {
      img: player,
      name: "문유현",
      backNum: 24,
      position: "G",
      studentId: 23,
      body: "181/78",
    },
    {
      img: player,
      name: "유민수",
      backNum: 7,
      position: "F",
      studentId: 23,
      body: "201/94",
    },
    {
      img: player,
      name: "윤기찬",
      backNum: 17,
      position: "F",
      studentId: 23,
      body: "194/91",
    },
    {
      img: player,
      name: "이동근",
      backNum: 18,
      position: "F",
      studentId: 23,
      body: "197/95",
    },
    {
      img: player,
      name: "이재민",
      backNum: 32,
      position: "C",
      studentId: 23,
      body: "198/105",
    },
  ],
  [
    //럭비  -->백넘버 확인해야함
    {
      img: player,
      name: "김찬주",
      backNum: 8,
      position: "N0.8",
      studentId: 20,
      body: "187/100",
    },
    {
      img: player,
      name: "원정호",
      backNum: 1,
      position: "Prop",
      studentId: 20,
      body: "180/120",
    },
    {
      img: player,
      name: "유성태",
      backNum: 9,
      position: "S.H",
      studentId: 20,
      body: "170/69",
    },
    {
      img: player,
      name: "이승은",
      backNum: 6,
      position: "Flanker",
      studentId: 20,
      body: "178/100",
    },
    {
      img: player,
      name: "이준우",
      backNum: 15,
      position: "F.B",
      studentId: 20,
      body: "187/95",
    },
    {
      img: player,
      name: "이현제",
      backNum: 12,
      position: "C.T.B",
      studentId: 20,
      body: "182/100",
    },
    {
      img: player,
      name: "주윤성",
      backNum: 13,
      position: "C.T.B",
      studentId: 20,
      body: "175/100",
    },
    {
      img: player,
      name: "최호영",
      backNum: 3,
      position: "Prop",
      studentId: 20,
      body: "178/120",
    },
    {
      img: player,
      name: "황정욱",
      backNum: 8,
      position: "No.8",
      studentId: 20,
      body: "188/110",
    },
    {
      img: player,
      name: "허동",
      backNum: 12,
      position: "C.T.B",
      studentId: 20,
      body: "180/93",
    },
    {
      img: player,
      name: "김용주",
      backNum: 3,
      position: "Prop",
      studentId: 21,
      body: "183/120",
    },
    {
      img: player,
      name: "김현진",
      backNum: 10,
      position: "S.O",
      studentId: 21,
      body: "179/79",
    },
    {
      img: player,
      name: "나태웅",
      backNum: 12,
      position: "C.T.B",
      studentId: 21,
      body: "185/94",
    },
    {
      img: player,
      name: "명정민",
      backNum: 5,
      position: "LOCK",
      studentId: 21,
      body: "193/120",
    },
    {
      img: player,
      name: "원영화",
      backNum: 9,
      position: "S.H",
      studentId: 21,
      body: "172/66",
    },
    {
      img: player,
      name: "이승준",
      backNum: 6,
      position: "Flanker",
      studentId: 21,
      body: "182/100",
    },
    {
      img: player,
      name: "이준이",
      backNum: 15,
      position: "F.B",
      studentId: 21,
      body: "175/77",
    },
    {
      img: player,
      name: "정민승",
      backNum: 6,
      position: "Flanker",
      studentId: 21,
      body: "177/100",
    },
    {
      img: player,
      name: "정준호",
      backNum: 11,
      position: "W.T.B",
      studentId: 21,
      body: "164/74",
    },
    {
      img: player,
      name: "김영민",
      backNum: 8,
      position: "No.8",
      studentId: 22,
      body: "180/95",
    },
    {
      img: player,
      name: "김정욱", //확인하기
      backNum: 13,
      position: "C.T.B",
      studentId: 22,
      body: "175/93",
    },
    {
      img: player,
      name: "박건태",
      backNum: 5,
      position: "LOCK",
      studentId: 22,
      body: "191/110",
    },
    {
      img: player,
      name: "박민규",
      backNum: 13,
      position: "C.T.B",
      studentId: 22,
      body: "172/82",
    },
    {
      img: player,
      name: "서예찬",
      backNum: 3,
      position: "Prop",
      studentId: 22,
      body: "183/118",
    },
    {
      img: player,
      name: "신의철",
      backNum: 2,
      position: "H.K",
      studentId: 22,
      body: "175/102",
    },
    {
      img: player,
      name: "오신균",
      backNum: 10,
      position: "S.O",
      studentId: 22,
      body: "174/85",
    },
    {
      img: player,
      name: "이문규",
      backNum: 15,
      position: "F.B",
      studentId: 22,
      body: "171/72",
    },
    {
      img: player,
      name: "이민재",
      backNum: 3,
      position: "Prop",
      studentId: 22,
      body: "180/113",
    },
    {
      img: player,
      name: "곽민기",
      backNum: 8,
      position: "No.8",
      studentId: 23,
      body: "185/95",
    },
    {
      img: player,
      name: "김세훈",
      backNum: 4,
      position: "LOCK",
      studentId: 23,
      body: "184/95",
    },
    {
      img: player,
      name: "김원주",
      backNum: 12,
      position: "C.T.B",
      studentId: 23,
      body: "185/95",
    },
    {
      img: player,
      name: "김재영",
      backNum: 13,
      position: "C.T.B",
      studentId: 23,
      body: "182/87",
    },
    {
      img: player,
      name: "김재완",
      backNum: 8,
      position: "No.8",
      studentId: 23,
      body: "180/92",
    },
    {
      img: player,
      name: "서현진",
      backNum: 1,
      position: "Prop",
      studentId: 23,
      body: "185/125",
    },
    {
      img: player,
      name: "심재윤",
      backNum: 5,
      position: "LOCK",
      studentId: 23,
      body: "186/100",
    },
    {
      img: player,
      name: "조성원",
      backNum: 3,
      position: "Prop",
      studentId: 23,
      body: "180/112",
    },
    {
      img: player,
      name: "홍민혁",
      backNum: 10,
      position: "S.O",
      studentId: 23,
      body: "175/78",
    },
  ],
  [
    //축구
    {
      img: player,
      name: "김수현",
      backNum: 19,
      position: "DF",
      studentId: 20,
      body: "182/78",
    },
    {
      img: player,
      name: "오상준",
      backNum: 4,
      position: "DF",
      studentId: 20,
      body: "183/82",
    },
    {
      img: player,
      name: "차주영",
      backNum: 21,
      position: "GK",
      studentId: 20,
      body: "178/73",
    },

    {
      img: player,
      name: "김기현",
      backNum: 11,
      position: "FW",
      studentId: 21,
      body: "186/79",
    },
    {
      img: player,
      name: "김채웅",
      backNum: 7,
      position: "FW",
      studentId: 21,
      body: "177/74",
    },
    {
      img: player,
      name: "방우진",
      backNum: 5,
      position: "DF",
      studentId: 21,
      body: "186/79",
    },
    {
      img: player,
      name: "유경민",
      backNum: 12,
      position: "FW",
      studentId: 21,
      body: "172/65",
    },
    {
      img: player,
      name: "이지호",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "183/74",
    },
    {
      img: player,
      name: "천세윤",
      backNum: 6,
      position: "MF",
      studentId: 21,
      body: "170/68",
    },

    {
      img: player,
      name: "강민준",
      backNum: 13,
      position: "DF",
      studentId: 22,
      body: "171/64",
    },
    {
      img: player,
      name: "권용승",
      backNum: 20,
      position: "DF",
      studentId: 22,
      body: "185/82",
    },
    {
      img: player,
      name: "김지호",
      backNum: 17,
      position: "FW",
      studentId: 22,
      body: "173/67",
    },
    {
      img: player,
      name: "동재민",
      backNum: 8,
      position: "MF",
      studentId: 22,
      body: "181/72",
    },
    {
      img: player,
      name: "성진영",
      backNum: 9,
      position: "FW",
      studentId: 22,
      body: "182/80",
    },
    {
      img: player,
      name: "신승민",
      backNum: 18,
      position: "MF",
      studentId: 22,
      body: "178/71",
    },
    {
      img: player,
      name: "정주선",
      backNum: 2,
      position: "DF",
      studentId: 22,
      body: "190/86",
    },
    {
      img: player,
      name: "최현승",
      backNum: 14,
      position: "DF",
      studentId: 22,
      body: "177/75",
    },
    {
      img: player,
      name: "황재윤",
      backNum: 1,
      position: "GK",
      studentId: 22,
      body: "187/83",
    },

    {
      img: player,
      name: "김민혁",
      backNum: 25,
      position: "DF",
      studentId: 23,
      body: "182/73",
    },
    {
      img: player,
      name: "김정훈",
      backNum: 31,
      position: "GK",
      studentId: 23,
      body: "188/81",
    },
    {
      img: player,
      name: "김지원",
      backNum: 27,
      position: "FW",
      studentId: 23,
      body: "189/87",
    },
    {
      img: player,
      name: "박찬이",
      backNum: 16,
      position: "MF",
      studentId: 23,
      body: "179/70",
    },
    {
      img: player,
      name: "송준휘",
      backNum: 3,
      position: "DF",
      studentId: 23,
      body: "186/81",
    },
    {
      img: player,
      name: "안혁주",
      backNum: 15,
      position: "FW",
      studentId: 23,
      body: "175/69",
    },
    {
      img: player,
      name: "양지섭",
      backNum: 23,
      position: "DF",
      studentId: 23,
      body: "171/71",
    },
    {
      img: player,
      name: "이유호",
      backNum: 22,
      position: "MF",
      studentId: 23,
      body: "179/73",
    },
    {
      img: player,
      name: "정의헌",
      backNum: 24,
      position: "DF",
      studentId: 23,
      body: "176/68",
    },
    {
      img: player,
      name: "조예성",
      backNum: 26,
      position: "DF",
      studentId: 23,
      body: "184/78",
    },
  ],
];
