import { IPlayer } from "../PlayerList";
import player from "../../../../public/image/player.svg";
//야구 빙구 농구 럭비 축구 순서
export const koreaPlayer: IPlayer[][] = [
  [
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
  ],
  [
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
  ],
  [
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
  ],
  [
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
  ],
  [
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player,
      name: "김기현",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
  ],
];
