import { IPlayer } from "../PlayerList";
import player2 from "../../../../public/image/player2.svg";

export const yonseiPlayer: IPlayer[][] = [
  [
    //야구
    {
      img: player2,
      name: "고경표",
      backNum: 3,
      position: "내야수",
      studentId: 20,
      body: "183/88",
    },
    {
      img: player2,
      name: "고승완",
      backNum: 17,
      position: "내야수",
      studentId: 20,
      body: "180/80",
    },
    {
      img: player2,
      name: "박계륜",
      backNum: 28,
      position: "투수",
      studentId: 20,
      body: "180/77",
    },
    {
      img: player2,
      name: "신효수",
      backNum: 26,
      position: "포수",
      studentId: 20,
      body: "178/82",
    },
    {
      img: player2,
      name: "성준한",
      backNum: 15,
      position: "외야수",
      studentId: 20,
      body: "174/66",
    },
    {
      img: player2,
      name: "이도겸",
      backNum: 36,
      position: "내야수",
      studentId: 20,
      body: "182/85",
    },
    {
      img: player2,
      name: "이승훈",
      backNum: 41,
      position: "투수",
      studentId: 20,
      body: "180/83",
    },
    {
      img: player2,
      name: "조성민",
      backNum: 47,
      position: "투수",
      studentId: 20,
      body: "178/72",
    },

    {
      img: player2,
      name: "김선재",
      backNum: 49,
      position: "투수",
      studentId: 21,
      body: "187/100",
    },
    {
      img: player2,
      name: "김진형",
      backNum: 8,
      position: "외야수",
      studentId: 21,
      body: "175/78",
    },
    {
      img: player2,
      name: "나병훈",
      backNum: 38,
      position: "투수",
      studentId: 21,
      body: "181/78",
    },
    {
      img: player2,
      name: "이동준",
      backNum: 17,
      position: "내야수",
      studentId: 21,
      body: "174/72",
    },
    {
      img: player2,
      name: "이우진",
      backNum: 12,
      position: "포수",
      studentId: 21,
      body: "180/95",
    },
    {
      img: player2,
      name: "권우재",
      backNum: 52,
      position: "내야수",
      studentId: 22,
      body: "180/93",
    },
    {
      img: player2,
      name: "두정민",
      backNum: 3,
      position: "외야수",
      studentId: 22,
      body: "178/85",
    },
    {
      img: player2,
      name: "양서준",
      backNum: 23,
      position: "내야수",
      studentId: 22,
      body: "176/74",
    },
    {
      img: player2,
      name: "엄지민",
      backNum: 18,
      position: "투수",
      studentId: 22,
      body: "182/76",
    },
    {
      img: player2,
      name: "윤성환",
      backNum: 41,
      position: "투수",
      studentId: 22,
      body: "185/90",
    },

    {
      img: player2,
      name: "이건희",
      backNum: 10,
      position: "포수",
      studentId: 22,
      body: "176/85",
    },
    {
      img: player2,
      name: "이찬영",
      backNum: 13,
      position: "내야수",
      studentId: 22,
      body: "178/77",
    },

    {
      img: player2,
      name: "강민구",
      backNum: 38,
      position: "투수",
      studentId: 23,
      body: "180/85",
    },
    {
      img: player2,
      name: "김동주",
      backNum: 22,
      position: "포수",
      studentId: 23,
      body: "179/84",
    },
    {
      img: player2,
      name: "김태양",
      backNum: 43,
      position: "투수",
      studentId: 23,
      body: "178/82",
    },
    {
      img: player2,
      name: "이지원",
      backNum: 9,
      position: "내야수",
      studentId: 23,
      body: "180/77",
    },
    {
      img: player2,
      name: "조영우",
      backNum: 47,
      position: "투수",
      studentId: 23,
      body: "182/81",
    },
    {
      img: player2,
      name: "조장현",
      backNum: 58,
      position: "외야수",
      studentId: 23,
      body: "178/77",
    },
    {
      img: player2,
      name: "홍서연",
      backNum: 27,
      position: "내야수",
      studentId: 23,
      body: "183/88",
    },
  ],
  [
    //빙구
    {
      img: player2,
      name: "김동환",
      backNum: 27,
      position: "DF",
      studentId: 20,
      body: "185/80",
    },
    {
      img: player2,
      name: "남경빈",
      backNum: 77,
      position: "DF",
      studentId: 20,
      body: "185/75",
    },
    {
      img: player2,
      name: "남기웅",
      backNum: 32,
      position: "FW",
      studentId: 20,
      body: "188/92",
    },
    {
      img: player2,
      name: "배상호",
      backNum: 18,
      position: "FW",
      studentId: 20,
      body: "175/75",
    },
    {
      img: player2,
      name: "박상진",
      backNum: 14,
      position: "FW",
      studentId: 21,
      body: "180/72",
    },
    {
      img: player2,
      name: "박준서",
      backNum: 43,
      position: "DF",
      studentId: 21,
      body: "180/74",
    },
    {
      img: player2,
      name: "신동현",
      backNum: 92,
      position: "FW",
      studentId: 21,
      body: "182/77",
    },
    {
      img: player2,
      name: "유태웅",
      backNum: 81,
      position: "DF",
      studentId: 21,
      body: "180/76",
    },
    {
      img: player2,
      name: "장가람",
      backNum: 70,
      position: "G",
      studentId: 21,
      body: "185/87",
    },
    {
      img: player2,
      name: "전혁준",
      backNum: 15,
      position: "FW",
      studentId: 21,
      body: "175/72",
    },
    {
      img: player2,
      name: "김용수",
      backNum: 23,
      position: "FW",
      studentId: 22,
      body: "174/73",
    },
    {
      img: player2,
      name: "문건오",
      backNum: 9,
      position: "FW",
      studentId: 22,
      body: "174/74",
    },
    {
      img: player2,
      name: "서지원",
      backNum: 8,
      position: "DF",
      studentId: 22,
      body: "177/76",
    },
    {
      img: player2,
      name: "송재원",
      backNum: 31,
      position: "G",
      studentId: 22,
      body: "174/70",
    },
    {
      img: player2,
      name: "이승재",
      backNum: 6,
      position: "DF",
      studentId: 22,
      body: "182/83",
    },
    {
      img: player2,
      name: "황재웅",
      backNum: 17,
      position: "FW",
      studentId: 22,
      body: "178/75",
    },

    {
      img: player2,
      name: "공유찬",
      backNum: 38,
      position: "DF",
      studentId: 23,
      body: "188/85",
    },
    {
      img: player2,
      name: "김다온",
      backNum: 11,
      position: "FW",
      studentId: 23,
      body: "177/75",
    },
    {
      img: player2,
      name: "김범석",
      backNum: 11,
      position: "FW",
      studentId: 23,
      body: "177/75",
    },
    {
      img: player2,
      name: "김시환",
      backNum: 13,
      position: "FW",
      studentId: 23,
      body: "177/75",
    },
    {
      img: player2,
      name: "이재현",
      backNum: 66,
      position: "FW",
      studentId: 23,
      body: "172/76",
    },
    {
      img: player2,
      name: "임동규",
      backNum: 15,
      position: "DF",
      studentId: 23,
      body: "190/82",
    },
    {
      img: player2,
      name: "홍승우",
      backNum: 55,
      position: "DF",
      studentId: 23,
      body: "177/77",
    },
  ],

  [
    //농구
    {
      img: player2,
      name: "김건우",
      backNum: 8,
      position: "F",
      studentId: 20,
      body: "199/96",
    },
    {
      img: player2,
      name: "유기상",
      backNum: 7,
      position: "G",
      studentId: 20,
      body: "190/78",
    },
    {
      img: player2,
      name: "강재민",
      backNum: 3,
      position: "F",
      studentId: 21,
      body: "195/83",
    },
    {
      img: player2,
      name: "김도완",
      backNum: 6,
      position: "G",
      studentId: 21,
      body: "178/68",
    },
    {
      img: player2,
      name: "최형찬",
      backNum: 17,
      position: "G",
      studentId: 21,
      body: "189/85",
    },
    {
      img: player2,
      name: "김보배",
      backNum: 2,
      position: "F/C", //두개로 써있음
      studentId: 22,
      body: "203/96",
    },
    {
      img: player2,
      name: "이민서",
      backNum: 1,
      position: "G",
      studentId: 22,
      body: "182/78",
    },
    {
      img: player2,
      name: "이규태",
      backNum: 23,
      position: "F/C",
      studentId: 22,
      body: "199/96",
    },
    {
      img: player2,
      name: "안성우",
      backNum: 11,
      position: "G",
      studentId: 22,
      body: "185/83",
    },
    {
      img: player2,
      name: "강지훈",
      backNum: 5,
      position: "C",
      studentId: 23,
      body: "202/96",
    },
    {
      img: player2,
      name: "이주영",
      backNum: 5,
      position: "G",
      studentId: 23,
      body: "190/83",
    },
    {
      img: player2,
      name: "이채형",
      backNum: 9,
      position: "G",
      studentId: 23,
      body: "187/78",
    },
    {
      img: player2,
      name: "이해솔",
      backNum: 4,
      position: "F",
      studentId: 23,
      body: "190/80",
    },
    {
      img: player2,
      name: "홍상민",
      backNum: 10,
      position: "G",
      studentId: 23,
      body: "200/100",
    },
  ],
  [
    //럭비
    {
      img: player2,
      name: "윤성",
      backNum: 9,
      position: "S.H",
      studentId: 20,
      body: "175/70",
    },
    {
      img: player2,
      name: "윤영민",
      backNum: 10,
      position: "C.T.B",
      studentId: 13,
      body: "187/100",
    },
    {
      img: player2,
      name: "이영민",
      backNum: 8,
      position: "No.8",
      studentId: 20,
      body: "175/80",
    },
    {
      img: player2,
      name: "이재욱",
      backNum: 15,
      position: "F.B",
      studentId: 20,
      body: "175/80",
    },
    {
      img: player2,
      name: "임성수",
      backNum: 4,
      position: "LOCK",
      studentId: 20,
      body: "183/90",
    },
    {
      img: player2,
      name: "장준범",
      backNum: 15,
      position: "F.B", //S.O, C.T.B도 써있음
      studentId: 20,
      body: "186/95",
    },

    {
      img: player2,
      name: "김지훈",
      backNum: 15,
      position: "F.B", //wing도 써있음
      studentId: 21,
      body: "171/75",
    },
    {
      img: player2,
      name: "김진성",
      backNum: 2,
      position: "H.K",
      studentId: 21,
      body: "172/92",
    },
    {
      img: player2,
      name: "김창혁",
      backNum: 8,
      position: "No.8", //flanker도 써있음
      studentId: 21,
      body: "185/95",
    },
    {
      img: player2,
      name: "서우현",
      backNum: 10,
      position: "S.O",
      studentId: 21,
      body: "178/82",
    },
    {
      img: player2,
      name: "이강민",
      backNum: 4,
      position: "LOCK",
      studentId: 21,
      body: "195/110",
    },
    {
      img: player2,
      name: "전인성",
      backNum: 9,
      position: "S.H", //wing도 써있음
      studentId: 22,
      body: "189/85",
    },
    {
      img: player2,
      name: "정재성",
      backNum: 5,
      position: "LOCK", //prop도 써있음
      studentId: 21,
      body: "187/108",
    },
    {
      img: player2,
      name: "황재동",
      backNum: 1,
      position: "Prop",
      studentId: 21,
      body: "176/115",
    },

    {
      img: player2,
      name: "김근우",
      backNum: 8,
      position: "No.8",
      studentId: 22,
      body: "185/100",
    },
    {
      img: player2,
      name: "김시원",
      backNum: 8,
      position: "No.8", //flanker도 써있음
      studentId: 22,
      body: "183/100",
    },
    {
      img: player2,
      name: "김민석",
      backNum: 3,
      position: "Prop",
      studentId: 22,
      body: "178/117",
    },
    {
      img: player2,
      name: "김지철",
      backNum: 15,
      position: "F.B",
      studentId: 22,
      body: "179/77",
    },
    {
      img: player2,
      name: "김태균",
      backNum: 10,
      position: "S.O",
      studentId: 22,
      body: "177/80",
    },
    {
      img: player2,
      name: "문병헌",
      backNum: 15,
      position: "F.B",
      studentId: 22,
      body: "178/85",
    },
    {
      img: player2,
      name: "오해성",
      backNum: 3,
      position: "Prop",
      studentId: 22,
      body: "184/125",
    },
    {
      img: player2,
      name: "옥성민",
      backNum: 10,
      position: "C.T.B",
      studentId: 22,
      body: "178/85",
    },
    {
      img: player2,
      name: "한준",
      backNum: 8,
      position: "No.8",
      studentId: 22,
      body: "188/110",
    },
    {
      img: player2,
      name: "황보상",
      backNum: 4,
      position: "LOCK",
      studentId: 22,
      body: "190/108",
    },

    {
      img: player2,
      name: "김도훈",
      backNum: 12,
      position: "C.T.B",
      studentId: 23,
      body: "173/90",
    },
    {
      img: player2,
      name: "김병관",
      backNum: 10,
      position: "S.O",
      studentId: 23,
      body: "178/78",
    },
    {
      img: player2,
      name: "박준서",
      backNum: 3,
      position: "Prop",
      studentId: 23,
      body: "175/115",
    },
    {
      img: player2,
      name: "서보성",
      backNum: 12,
      position: "C.T.B",
      studentId: 23,
      body: "185/95",
    },
    {
      img: player2,
      name: "손효",
      backNum: 3,
      position: "Prop",
      studentId: 23,
      body: "187/118",
    },

    {
      img: player2,
      name: "임민규",
      backNum: 5,
      position: "LOCK",
      studentId: 23,
      body: "189/110",
    },
    {
      img: player2,
      name: "이세빈",
      backNum: 15,
      position: "F.B",
      studentId: 23,
      body: "177/80",
    },
    {
      img: player2,
      name: "조현재",
      backNum: 8,
      position: "No.8",
      studentId: 23,
      body: "182/93",
    },
    {
      img: player2,
      name: "최규락",
      backNum: 8,
      position: "No.8",
      studentId: 23,
      body: "185/103",
    },
    {
      img: player2,
      name: "허윤혁",
      backNum: 12,
      position: "C.T.B",
      studentId: 23,
      body: "174/95",
    },
  ],
  [
    //축구
    {
      img: player2,
      name: "장재혁",
      backNum: 26,
      position: "DF",
      studentId: 20,
      body: "180/76",
    },
    {
      img: player2,
      name: "최형우",
      backNum: 22,
      position: "MF",
      studentId: 20,
      body: "178/74",
    },

    {
      img: player2,
      name: "박지상",
      backNum: 23,
      position: "MF",
      studentId: 21,
      body: "176/68",
    },
    {
      img: player2,
      name: "박호인",
      backNum: 25,
      position: "FW",
      studentId: 21,
      body: "177/74",
    },
    {
      img: player2,
      name: "이재근",
      backNum: 3,
      position: "DF",
      studentId: 21,
      body: "178/70",
    },
    {
      img: player2,
      name: "장유민",
      backNum: 16,
      position: "DF",
      studentId: 21,
      body: "179/73",
    },

    {
      img: player2,
      name: "진시우",
      backNum: 20,
      position: "DF",
      studentId: 21,
      body: "189/79",
    },
    {
      img: player2,
      name: "하재민",
      backNum: 14,
      position: "MF",
      studentId: 21,
      body: "186/90",
    },
    {
      img: player2,
      name: "강민재",
      backNum: 10,
      position: "FW",
      studentId: 22,
      body: "184/80",
    },
    {
      img: player2,
      name: "박건희",
      backNum: 9,
      position: "FW",
      studentId: 22,
      body: "177/71",
    },
    {
      img: player2,
      name: "박시영",
      backNum: 2,
      position: "DF",
      studentId: 22,
      body: "175/70",
    },
    {
      img: player2,
      name: "양태웅",
      backNum: 26,
      position: "DF",
      studentId: 22,
      body: "186/81",
    },
    {
      img: player2,
      name: "장현도",
      backNum: 7,
      position: "DF",
      studentId: 22,
      body: "170/66",
    },
    {
      img: player2,
      name: "진의준",
      backNum: 13,
      position: "MF",
      studentId: 22,
      body: "173/70",
    },
    {
      img: player2,
      name: "최우진",
      backNum: 24,
      position: "DF",
      studentId: 22,
      body: "177/72",
    },
    {
      img: player2,
      name: "황승우",
      backNum: 17,
      position: "FW",
      studentId: 22,
      body: "177/75",
    },

    {
      img: player2,
      name: "곽민석",
      backNum: 8,
      position: "MF",
      studentId: 23,
      body: "179/73",
    },
    {
      img: player2,
      name: "강민서",
      backNum: 4,
      position: "DF",
      studentId: 23,
      body: "183/78",
    },
    {
      img: player2,
      name: "강진엽",
      backNum: 15,
      position: "DF",
      studentId: 23,
      body: "179/73",
    },
    {
      img: player2,
      name: "이승민",
      backNum: 6,
      position: "DF",
      studentId: 23,
      body: "184/80",
    },
    {
      img: player2,
      name: "장하민",
      backNum: 12,
      position: "FW",
      studentId: 23,
      body: "178/71",
    },
    {
      img: player2,
      name: "장현빈",
      backNum: 11,
      position: "FW",
      studentId: 23,
      body: "179/73",
    },
    {
      img: player2,
      name: "최강서",
      backNum: 21,
      position: "GK",
      studentId: 23,
      body: "187/78",
    },
    {
      img: player2,
      name: "최지웅",
      backNum: 18,
      position: "MF",
      studentId: 23,
      body: "171/65",
    },
  ],
];
