import { IPlayer } from "../PlayerList";
import player2 from "../../../../public/image/player2.svg";

export const yonseiPlayer: IPlayer[][] = [
  [
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
  ],
  [
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
  ],
  [
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
  ],
  [
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
  ],
  [
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
    {
      img: player2,
      name: "이민혁",
      backNum: 10,
      position: "FW",
      studentId: 21,
      body: "180/70",
    },
  ],
];
